title: USC IMPACT LAB
description: Intelligent Machines for People through AI and Computing Technologies.
url: "https://impact-usc.github.io"
baseurl: ""
email: yjin@usc.edu
github_username: impact-usc

theme: null

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - assets/Presentation1.pptx
